name: Lint and Test Charts

on:
  push:
    branches:
      - dev
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@master
        with:
          command: lint
          config: .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.12.10
          - v1.13.12
          - v1.14.10
          - v1.15.7
          - v1.15.11
          - v1.16.4
          - v1.16.8
          - v1.17.4
          - v1.18.1
          - v1.19.0
        chart:
          - renovate
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Helm2Kube conversion
        run: helm template --values "charts/${{ matrix.chart }}/ci/ci-values.yaml" "charts/${{ matrix.chart }}" --output-dir tmp/${{ matrix.k8s }}/${{ matrix.chart }}
      - name: Run kubeval
        uses: instrumenta/kubeval-action@master
        with:
          version: ${{ matrix.k8s }}
          files: tmp/${{ matrix.k8s }}/${{ matrix.chart }}
          strict: true
          ignore_missing_schemas: true

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeval-chart
    strategy:
      matrix:
        k8s:
          - v1.12.10
          - v1.13.12
          - v1.14.10
          - v1.15.7
          - v1.15.11
          - v1.16.4
          - v1.16.9
          - v1.17.2
          - v1.17.5
          - v1.18.8
          - v1.19.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@master
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@master
        with:
          command: install
          config: .github/ct.yaml
